# Exported from Render on 2024-08-12T18:29:08Z
services:
- type: web
  name: NikosTechBlog
  runtime: node
  repo: https://github.com/NikoMayz/NikosTechBlog
  plan: free
  envVars:
  - key: NODE_VERSION
    sync: false
  - key: DB_DIALECT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  region: virginia
  buildCommand: npm install
  startCommand: node server.js
version: "1"
